name: Release

on: 
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_SH: build.sh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Get REPO Name'
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/wei2ard\/nros-//')" >> $GITHUB_ENV

    - name: 'Get Version'
      run: |
        echo "versionCN=$(sed -n 1p ./CN/changelog.md | sed "s/##\s//")" >> $GITHUB_ENV
        echo "versionEN=$(sed -n 1p ./EN/changelog.md | sed "s/##\s//")" >> $GITHUB_ENV
        echo "versionRU=$(sed -n 1p ./RU/changelog.md | sed "s/##\s//")" >> $GITHUB_ENV

    - name: 'Build'
      run: |
        chmod +x $BUILD_SH
        ./$BUILD_SH

    - name: 'Release'
      uses: softprops/action-gh-release@master
      with:
        draft: false
        tag_name: 'latest'
        files: |
          ./${{env.REPO}}_CN.zip
          ./${{env.REPO}}_EN.zip
          ./${{env.REPO}}_RU.zip

    - name: 'Upload'
      run: |
        mv ./RU/changelog.md ./RU/更新日志.md
        mv ./${{env.REPO}}_RU.zip ./RU/${{env.REPO}}_${{env.versionRU}}_RU.zip
        curl -T '{./RU/${{env.REPO}}_${{env.versionRU}}_RU.zip,./RU/更新日志.md}' -u ${{ secrets.WEBDAV_TOKEN }} 'https://dav.jianguoyun.com/dav/switch/${{env.REPO}}/'